#include "Triangle.h"
#include <FunctionLayer/Acceleration/Linear.h>
//--- Triangle ---
Triangle::Triangle(int _primID, int _vtx0Idx, int _vtx1Idx, int _vtx2Idx,
                   const TriangleMesh *_mesh)
    : primID(_primID), vtx0Idx(_vtx0Idx), vtx1Idx(_vtx1Idx), vtx2Idx(_vtx2Idx),
      mesh(_mesh) {
  Point3f vtx0 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx0Idx]),
          vtx1 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx1Idx]),
          vtx2 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx2Idx]);
  boundingBox.Expand(vtx0);
  boundingBox.Expand(vtx1);
  boundingBox.Expand(vtx2);
  this->geometryID = mesh->geometryID;
}

bool Triangle::rayIntersectShape(Ray &ray, int *primID, float *u,
                                 float *v) const {
  Point3f p0 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx0Idx]),
          p1 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx1Idx]),
          p2 = mesh->transform.toWorld(mesh->meshData->vertexBuffer[vtx2Idx]);

  Vector3f edge1 = p1 - p0, edge2 = p2 - p0;
  Vector3f pvec = cross(ray.direction, edge2);
  float det = dot(edge1, pvec);
  if (std::abs(det) < EPSILON) {
    return false;
  }

  float invDet = 1.f / det;
  Vector3f tvec = ray.origin - p0;
  float bary1 = dot(tvec, pvec) * invDet;
  if (bary1 < .0f || bary1 > 1.f) {
    return false;
  }

  Vector3f qvec = cross(tvec, edge1);
  float bary2 = dot(ray.direction, qvec) * invDet;
  if (bary2 < .0f || bary1 + bary2 > 1.f) {
    return false;
  }

  float t = dot(edge2, qvec) * invDet;
  if (t < ray.tNear || t > ray.tFar) {
    return false;
  }

  ray.tFar = t;
  *primID = this->primID;
  *u = bary1;
  *v = bary2;
  return true;
}

void Triangle::fillIntersection(float distance, int primID, float u, float v,
                                Intersection *intersection) const {
  // 该函数实际上不会被调用
  return;
}

//--- TriangleMesh ---
TriangleMesh::TriangleMesh(const Json &json) : Shape(json) {
  const auto &filepath = fetchRequired<std::string>(json, "file");
  meshData = MeshData::loadFromFile(filepath);
}

RTCGeometry TriangleMesh::getEmbreeGeometry(RTCDevice device) const {
  RTCGeometry geometry = rtcNewGeometry(device, RTC_GEOMETRY_TYPE_TRIANGLE);

  float *vertexBuffer = (float *)rtcSetNewGeometryBuffer(
      geometry, RTC_BUFFER_TYPE_VERTEX, 0, RTC_FORMAT_FLOAT3, 3 * sizeof(float),
      meshData->vertexCount);
  for (int i = 0; i < meshData->vertexCount; ++i) {
    Point3f vertex = transform.toWorld(meshData->vertexBuffer[i]);
    vertexBuffer[3 * i] = vertex[0];
    vertexBuffer[3 * i + 1] = vertex[1];
    vertexBuffer[3 * i + 2] = vertex[2];
  }

  unsigned *indexBuffer = (unsigned *)rtcSetNewGeometryBuffer(
      geometry, RTC_BUFFER_TYPE_INDEX, 0, RTC_FORMAT_UINT3,
      3 * sizeof(unsigned), meshData->faceCount);
  for (int i = 0; i < meshData->faceCount; ++i) {
    indexBuffer[i * 3] = meshData->faceBuffer[i][0].vertexIndex;
    indexBuffer[i * 3 + 1] = meshData->faceBuffer[i][1].vertexIndex;
    indexBuffer[i * 3 + 2] = meshData->faceBuffer[i][2].vertexIndex;
  }
  rtcCommitGeometry(geometry);
  return geometry;
}

bool TriangleMesh::rayIntersectShape(Ray &ray, int *primID, float *u,
                                     float *v) const {
  //* 当使用embree加速时，该方法不会被调用
  int geomID = -1;
  return acceleration->rayIntersect(ray, &geomID, primID, u, v);
}

void TriangleMesh::fillIntersection(float distance, int primID, float u,
                                    float v, Intersection *intersection) const {
  intersection->distance = distance;
  intersection->shape = this;

  // Generated by AI, since I don't know why this is a to-do but not part of the lab.
  const auto &face = meshData->faceBuffer[primID];
  float w = 1.f - u - v;

  int v0Idx = face[0].vertexIndex, v1Idx = face[1].vertexIndex,
      v2Idx = face[2].vertexIndex;
  Point3f p0 = transform.toWorld(meshData->vertexBuffer[v0Idx]),
          p1 = transform.toWorld(meshData->vertexBuffer[v1Idx]),
          p2 = transform.toWorld(meshData->vertexBuffer[v2Idx]);
  Vector3f dp1 = p1 - p0, dp2 = p2 - p0;

  intersection->position = p0 + u * dp1 + v * dp2;

  Vector3f geometricNormal = normalize(cross(dp1, dp2));
  Vector3f normal = geometricNormal;
  int n0Idx = face[0].normalIndex, n1Idx = face[1].normalIndex,
      n2Idx = face[2].normalIndex;
  if (n0Idx >= 0 && n1Idx >= 0 && n2Idx >= 0 &&
      n0Idx < meshData->normalBuffer.size() &&
      n1Idx < meshData->normalBuffer.size() &&
      n2Idx < meshData->normalBuffer.size()) {
    Vector3f n0 = normalize(transform.toWorld(meshData->normalBuffer[n0Idx])),
             n1 = normalize(transform.toWorld(meshData->normalBuffer[n1Idx])),
             n2 = normalize(transform.toWorld(meshData->normalBuffer[n2Idx]));
    normal = w * n0 + u * n1 + v * n2;
    if (normal.length() < EPSILON) {
      normal = geometricNormal;
    } else {
      normal = normalize(normal);
    }
  }
  intersection->normal = normal;

  Vector2f texCoord{u, v};
  bool hasUV = false;
  Vector2f uv0, uv1, uv2;
  int uv0Idx = face[0].texcodIndex, uv1Idx = face[1].texcodIndex,
      uv2Idx = face[2].texcodIndex;
  if (uv0Idx >= 0 && uv1Idx >= 0 && uv2Idx >= 0 &&
      uv0Idx < meshData->texcodBuffer.size() &&
      uv1Idx < meshData->texcodBuffer.size() &&
      uv2Idx < meshData->texcodBuffer.size()) {
    uv0 = meshData->texcodBuffer[uv0Idx];
    uv1 = meshData->texcodBuffer[uv1Idx];
    uv2 = meshData->texcodBuffer[uv2Idx];
    texCoord = w * uv0 + u * uv1 + v * uv2;
    hasUV = true;
  }
  intersection->texCoord = texCoord;

  Vector3f tangent, bitangent, dpdu, dpdv;
  if (hasUV) {
    Vector2f duv1 = uv1 - uv0, duv2 = uv2 - uv0;
    float det = duv1[0] * duv2[1] - duv1[1] * duv2[0];
    if (std::abs(det) > EPSILON) {
      float invDet = 1.f / det;
      dpdu = (duv2[1] * dp1 - duv1[1] * dp2) * invDet;
      dpdv = (-duv2[0] * dp1 + duv1[0] * dp2) * invDet;
    }
  }
  if (dpdu.length() < EPSILON || dpdv.length() < EPSILON) {
    dpdu = dp1;
    if (dpdu.length() < EPSILON) {
      dpdu = Vector3f(1.f, .0f, .0f);
    }
    dpdu = normalize(dpdu);
    dpdv = cross(normal, dpdu);
    if (dpdv.length() < EPSILON) {
      dpdu = Vector3f(.0f, 1.f, .0f);
      dpdv = cross(normal, dpdu);
    }
    dpdv = normalize(dpdv);
  }
  tangent = dpdu - dot(dpdu, normal) * normal;
  if (tangent.length() < EPSILON) {
    tangent = cross(Vector3f{1.f, .0f, .0f}, normal);
    if (tangent.length() < EPSILON) {
      tangent = cross(Vector3f{.0f, 1.f, .0f}, normal);
    }
  }
  tangent = normalize(tangent);
  bitangent = normalize(cross(tangent, normal));

  intersection->dpdu = dpdu;
  intersection->dpdv = dpdv;
  intersection->tangent = tangent;
  intersection->bitangent = bitangent;
}

void TriangleMesh::initInternalAcceleration() {
  acceleration = Acceleration::createAcceleration();
  int primCount = meshData->faceCount;
  for (int primID = 0; primID < primCount; ++primID) {
    int vtx0Idx = meshData->faceBuffer[primID][0].vertexIndex,
        vtx1Idx = meshData->faceBuffer[primID][1].vertexIndex,
        vtx2Idx = meshData->faceBuffer[primID][2].vertexIndex;
    std::shared_ptr<Triangle> triangle =
        std::make_shared<Triangle>(primID, vtx0Idx, vtx1Idx, vtx2Idx, this);
    acceleration->attachShape(triangle);
  }
  acceleration->build();
  // TriangleMesh的包围盒就是其内部加速结构的包围盒
  boundingBox = acceleration->boundingBox;
}
REGISTER_CLASS(TriangleMesh, "triangle")